// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClearIntelliSenseCache
{
    internal sealed partial class Vsix
    {
        public const string Id = "ClearIntelliSenseCache.144e5920-4b44-455c-8ac4-5fdcd17838fb";
        public const string Name = "Clear Solution IntelliSense Cache";
        public const string Description = @"Clears the solution IntelliSense cache to fix issues with broken IntelliSense at design time, such as false or missing compile errors, etc.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Helixoft";
        public const string Tags = "clear, fix, broken, corrupt, IntelliSense, cache";
    }
}
