// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClearIntelliSenseCache
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ClearIntelliSenseCacheString = "ac3fa4e9-7ecd-4517-b7b4-2115c00bb0c4";
        public static Guid ClearIntelliSenseCache = new Guid(ClearIntelliSenseCacheString);

        public const string UICONTEXT_SolutionExistsString = "f1536ef8-92ec-443c-9ed7-fdadf150da82";
        public static Guid UICONTEXT_SolutionExists = new Guid(UICONTEXT_SolutionExistsString);

        public const string UICONTEXT_SolutionHasSingleProjectString = "adfc4e66-0397-11d1-9f4e-00a0c911004f";
        public static Guid UICONTEXT_SolutionHasSingleProject = new Guid(UICONTEXT_SolutionHasSingleProjectString);

        public const string UICONTEXT_SolutionHasMultipleProjectsString = "93694fa0-0397-11d1-9f4e-00a0c911004f";
        public static Guid UICONTEXT_SolutionHasMultipleProjects = new Guid(UICONTEXT_SolutionHasMultipleProjectsString);

        public const string UICONTEXT_SolutionExistsAndFullyLoadedString = "10534154-102d-46e2-aba8-a6bfa25ba0be";
        public static Guid UICONTEXT_SolutionExistsAndFullyLoaded = new Guid(UICONTEXT_SolutionExistsAndFullyLoadedString);

        public const string UICONTEXT_SolutionExistsAndNotBuildingAndNotDebuggingString = "d0e4deec-1b53-4cda-8559-d454583ad23b";
        public static Guid UICONTEXT_SolutionExistsAndNotBuildingAndNotDebugging = new Guid(UICONTEXT_SolutionExistsAndNotBuildingAndNotDebuggingString);

        public const string UICONTEXT_SolutionBuildingString = "adfc4e60-0397-11d1-9f4e-00a0c911004f";
        public static Guid UICONTEXT_SolutionBuilding = new Guid(UICONTEXT_SolutionBuildingString);

        public const string UICONTEXT_EmptySolutionString = "adfc4e65-0397-11d1-9f4e-00a0c911004f";
        public static Guid UICONTEXT_EmptySolution = new Guid(UICONTEXT_EmptySolutionString);

        public const string UICONTEXT_NoSolutionString = "adfc4e64-0397-11d1-9f4e-00a0c911004f";
        public static Guid UICONTEXT_NoSolution = new Guid(UICONTEXT_NoSolutionString);

        public const string UICONTEXT_SolutionOpeningString = "d2567162-f94f-4091-8798-a096e61b8b50";
        public static Guid UICONTEXT_SolutionOpening = new Guid(UICONTEXT_SolutionOpeningString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ClearIntellisenseCommand = 0x0100;
    }
}